name: sysrepo-plugin-snabb CI

on:
  push:
    branches: ["devel"]
  pull_request:
    branches: ["devel"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: deps-libyang
        shell: bash
        run: |
          git clone https://github.com/cesnet/libyang
          cd libyang
          CC=gcc cmake -B build
          cmake --build build
          sudo cmake --install build
          sudo ldconfig
          cd ..

      - name: Deps-sysrepo
        shell: bash
        run: |
          git clone https://github.com/sysrepo/sysrepo
          cd sysrepo
          CC=gcc cmake -B build
          cmake --build build
          sudo cmake --install build
          cd build
          make shm_clean
          sudo ldconfig
          cd ../..

      - name: Deps-snabb
        shell: bash
        run: |
          git clone https://github.com/SnabbCo/snabb
          cd snabb
          make -j4 && sudo make install 
          sudo ldconfig
          cd ..

      - name: Snabb-plugin
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          #sudo chmod 777 /lib/systemd/system
          sudo cmake -B build  -DSR_PLUGINS_DIR=/usr/local/lib/ \
                  -DYANG_MODEL:String="snabb-softwire-v3"
          cd build
          sudo make -j4 
          sudo make install 
          sudo ldconfig
          sudo cp sysrepo-snabb-plugin /usr/local/bin
          cd ..

      - name: Install-yang-model
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          sysrepoctl -i snabb/src/lib/yang/snabb-softwire-v3.yang

      - name: run-tests
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          export LIBYANG_HEADERS=/usr/local/include
          export LIBYANG_LIBRARIES=/usr/local/lib
          export SYSREPO_HEADERS=/usr/local/include
          export SYSREPO_LIBRARIES=/usr/local/lib
          cd sysrepo/build
          make shm_clean
          cd ../..
          sysrepocfg -X -x "/snabb-softwire-v3:softwire-config/instance/external-device"
          #cd tests/robot-tests
          #sudo ./setup.sh
          #source ./test-venv/bin/activate
          #robot src/Main.robot
